name: 'build'

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update
        run: |
          sudo apt-get update -yqq
          sudo apt-get install bc -yqq
      - name: Build Kernel
        run: |
          sudo bash build-kernel
          cp linux-msft-wsl-*/vmlinux .
      - name: Upload Kernel
        uses: actions/upload-artifact@v3
        with:
          name: vmlinux
          path: vmlinux
